keys:
  - &backup age1jxn3arlu0h070azaau6g9s59k7ly4m9mhfkscj4rwgxra0utz9vq995pqw
  - &alsafi age1tc79fsdfm6q7wgu2eryx20fc3r4rw3ezspptkg3hwxy6m87n4ynq6ehg82
  - &luna age1qxyfrujl9zxw5rzyjdexf3l3vyly3r648658qnt394fgnmw52u9sq3p7jl
  - &sol age1w8qq3n7ak37g3dnhqa7ltj7yerwps2y934xh9lnzk4eumdmyd5csw8nzj4
  - &vega age10pfm9mam7cnc5j4fw80wp9l8629al6qdqn60hzxq9mdaszhef4vq529zgn
creation_rules:
  - path_regex: ^mundus/secrets\.yaml$
    key_groups:
    - age:
      - *backup
      - *alsafi
      - *luna
      - *sol
      - *vega
  - path_regex: ^loci/alsafi/secrets\.yaml$
    key_groups:
    - age:
      - *backup
      - *alsafi
  - path_regex: ^loci/luna/secrets\.yaml$
    key_groups:
    - age:
      - *backup
      - *luna
  - path_regex: ^loci/sol/secrets\.yaml$
    key_groups:
    - age:
      - *backup
      - *sol
  - path_regex: ^loci/vega/secrets\.yaml$
    key_groups:
    - age:
      - *backup
      - *vega
