keys:
  - &carter FBC4744684FF0E9536C85BB1D8F164413DAAA9D2
  - &alsafi age1tc79fsdfm6q7wgu2eryx20fc3r4rw3ezspptkg3hwxy6m87n4ynq6ehg82
  - &altair age1uxucdl6paw9z5uhrav3h8cepww5juuv9dner72hde3a56mhnza7qy5cvu8
  - &luna age1qxyfrujl9zxw5rzyjdexf3l3vyly3r648658qnt394fgnmw52u9sq3p7jl
  - &sol age1w8qq3n7ak37g3dnhqa7ltj7yerwps2y934xh9lnzk4eumdmyd5csw8nzj4
  - &vega age10pfm9mam7cnc5j4fw80wp9l8629al6qdqn60hzxq9mdaszhef4vq529zgn
creation_rules:
- path_regex: ^mundus/secrets\.yaml$
  key_groups:
  - pgp:
    - *carter
    age:
    - *alsafi
    - *altair
    - *luna
    - *sol
    - *vega
- path_regex: ^loci/alsafi/secrets\.yaml$
  pgp: *carter
  age: *alsafi
- path_regex: ^loci/altair/secrets\.yaml$
  pgp: *carter
  age: *altair
- path_regex: ^loci/luna/secrets\.yaml$
  pgp: *carter
  age: *luna
- path_regex: ^loci/sol/secrets\.yaml$
  pgp: *carter
  age: *sol
- path_regex: ^loci/vega/secrets\.yaml$
  pgp: *carter
  age: *vega
