keys:
  - &backup age1jxn3arlu0h070azaau6g9s59k7ly4m9mhfkscj4rwgxra0utz9vq995pqw
  - &alsafi age1x2e63nrdefg2mj6rurv8tfxupr6dgndh8wl6wtlg5tghx9gr2puqaj8tp7
  - &luna age1qxyfrujl9zxw5rzyjdexf3l3vyly3r648658qnt394fgnmw52u9sq3p7jl
  - &sol age1w8qq3n7ak37g3dnhqa7ltj7yerwps2y934xh9lnzk4eumdmyd5csw8nzj4
  - &vega age1u2d4vzua87grq0rsrjp5zp3k8juxwmvtcghs60qgywcgaqyrgc9qq4jg0x
creation_rules:
  - path_regex: ^mundus/secrets\.yaml$
    key_groups:
    - age:
      - *backup
      - *alsafi
      - *luna
      - *sol
      - *vega
  - path_regex: ^loci/alsafi/secrets\.yaml$
    key_groups:
    - age:
      - *backup
      - *alsafi
  - path_regex: ^loci/luna/secrets\.yaml$
    key_groups:
    - age:
      - *backup
      - *luna
  - path_regex: ^loci/sol/secrets\.yaml$
    key_groups:
    - age:
      - *backup
      - *sol
  - path_regex: ^loci/vega/secrets\.yaml$
    key_groups:
    - age:
      - *backup
      - *vega
